### ISSUE TITLE
0-fs panic with a nil pointer exception

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/0-fs#43]
This has happened randomly before. (version 2.0.5) 

```
goroutine 650422 [running]:
github.com/threefoldtech/0-fs/meta.(*Dir).Name(0x0, 0xc0033f8980, 0x5)
	/gopath/src/github.com/threefoldtech/0-fs/meta/dir.go:31 +0x22
github.com/threefoldtech/0-fs/meta.(*sqlStore).get(0xc000176a80, 0xc001d26eb0, 0x42, 0x10, 0x964300, 0xc0010e5c01, 0xc0033d1340)
	/gopath/src/github.com/threefoldtech/0-fs/meta/store.go:253 +0x1dd
github.com/threefoldtech/0-fs/meta.(*sqlStore).Get(0xc000176a80, 0xc001d26eb0, 0x42, 0xc0033d1340, 0x1, 0x1)
	/gopath/src/github.com/threefoldtech/0-fs/meta/store.go:267 +0x3f
github.com/threefoldtech/0-fs/rofs.(*filesystem).GetAttr(0xc000168bc0, 0xc001d26eb0, 0x42, 0xc002d84858, 0x0, 0x0)
	/gopath/src/github.com/threefoldtech/0-fs/rofs/rofs.go:69 +0x159
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs.(*readonlyFileSystem).GetAttr(0xc0001ba240, 0xc001d26eb0, 0x42, 0xc002d84858, 0xc0039ac000, 0xc0010e5e78)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs/readonlyfs.go:26 +0x51
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).GetAttr(0xc00070d2f0, 0xc002d847c0, 0x0, 0x0, 0xc002d84858, 0x481a5c)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:603 +0x7c
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).GetAttr(0xc000176db0, 0xc002d84840, 0xc002d847b0, 0x958b20)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:139 +0x88
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.doGetAttr(0xc0001d2000, 0xc002d846c0)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/opcode.go:246 +0x64
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc0001d2000, 0xc002d846c0, 0xc002d846c0)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:404 +0x30c
github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc0001d2000, 0xc002c59c01)
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:376 +0x14d
created by github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/gopath/src/github.com/threefoldtech/0-fs/vendor/github.com/hanwen/go-fuse/fuse/server.go:284 +0x332
```

**Comment by muhamadazmy** [comment]
Flist: https://hub.grid.tf/ahmedelsayed.3bot/threefoldtech-js-sdk-latest.flist

**Comment by muhamadazmy** [comment]
This this stacktrace is from a really older version because the lines do not match
